version: "3.8"

services:
  frontend:
    image: ghcr.io/pauta-cidada/frontend:latest
    environment:
      NODE_ENV: production
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.pautacidada_frontend.rule=Host(`pautacidada.com.br`)
        - traefik.http.routers.pautacidada_frontend.service=pautacidada_frontend
        - traefik.http.routers.pautacidada_frontend.entrypoints=websecure
        - traefik.http.routers.pautacidada_frontend.tls.certresolver=le
        - traefik.http.routers.pautacidada_frontend.tls=true
        - traefik.http.services.pautacidada_frontend.loadbalancer.server.port=3000
    networks:
      - traefik_public

  backend-python:
    image: ghcr.io/pauta-cidada/backend-python:latest
    environment:
      # Supabase
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_BUCKET_NAME: ${SUPABASE_BUCKET_NAME}
      # Database
      DATABASE_URL: ${DATABASE_URL}
      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Google Cloud BigQuery
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.pautacidada_api.rule=Host(`api.pautacidada.com.br`)
        - traefik.http.routers.pautacidada_api.service=pautacidada_api
        - traefik.http.routers.pautacidada_api.entrypoints=websecure
        - traefik.http.routers.pautacidada_api.tls.certresolver=le
        - traefik.http.routers.pautacidada_api.tls=true
        - traefik.http.services.pautacidada_api.loadbalancer.server.port=80
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
    driver: overlay
    driver_opts:
      com.docker.network.enable_ipv6: "true"
